env:
  browser: true
  es2021: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:  {
      "no-await-in-loop": "off",
      "no-console": "off",
      "no-restricted-syntax": "off",
      "import/extensions": 1
}
